name: deploy
on:
  push:
    branches:
      - 'main'
jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build
      - run: cd docs/.vitepress/dist
      - run: git init
      - run: git add -A
      - run: git commit -m 'deploy'
      - run: git push -f git@github.com:jp-liu/learn-git-actions.git main:gh-pages
      - run: cd -
